// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from "./core/CancelablePromise";
import { OpenAPI } from "./core/OpenAPI";
import { request as __request } from "./core/request";
import type {
  ItemsReadItemsData,
  ItemsReadItemsResponse,
  ItemsCreateItemData,
  ItemsCreateItemResponse,
  ItemsReadItemData,
  ItemsReadItemResponse,
  ItemsUpdateItemData,
  ItemsUpdateItemResponse,
  ItemsDeleteItemData,
  ItemsDeleteItemResponse,
  LoginLoginAccessTokenData,
  LoginLoginAccessTokenResponse,
  LoginTestTokenResponse,
  LoginRecoverPasswordData,
  LoginRecoverPasswordResponse,
  LoginResetPasswordData,
  LoginResetPasswordResponse,
  LoginRecoverPasswordHtmlContentData,
  LoginRecoverPasswordHtmlContentResponse,
  PrivateCreateUserData,
  PrivateCreateUserResponse,
  UsersReadUsersData,
  UsersReadUsersResponse,
  UsersCreateUserData,
  UsersCreateUserResponse,
  UsersReadUserMeResponse,
  UsersDeleteUserMeResponse,
  UsersUpdateUserMeData,
  UsersUpdateUserMeResponse,
  UsersUpdatePasswordMeData,
  UsersUpdatePasswordMeResponse,
  UsersRegisterUserData,
  UsersRegisterUserResponse,
  UsersReadUserByIdData,
  UsersReadUserByIdResponse,
  UsersUpdateUserData,
  UsersUpdateUserResponse,
  UsersDeleteUserData,
  UsersDeleteUserResponse,
  UtilsTestEmailData,
  UtilsTestEmailResponse,
  UtilsHealthCheckResponse,
  ProductsReadProductsData,
  ProductsReadProductsResponse,
  ProductsCreateProductData,
  ProductsCreateProductResponse,
  ProductsReadProductData,
  ProductsReadProductResponse,
  ProductsUpdateProductData,
  ProductsUpdateProductResponse,
  ProductsDeleteProductData,
  ProductsDeleteProductResponse,
  CategoriesReadCategoriesData,
  CategoriesReadCategoriesResponse,
  CategoriesCreateCategoryData,
  CategoriesCreateCategoryResponse,
  CategoriesReadCategoryData,
  CategoriesReadCategoryResponse,
  CategoriesUpdateCategoryData,
  CategoriesUpdateCategoryResponse,
  CategoriesDeleteCategoryData,
  CategoriesDeleteCategoryResponse,
  MovementsReadMovementsData,
  MovementsReadMovementsResponse,
  MovementsCreateMovementData,
  MovementsCreateMovementResponse,
  MovementsReadMovementData,
  MovementsReadMovementResponse,
  ReportsGetSalesReportData,
  ReportsGetSalesReportResponse,
  ReportsGetPurchasesReportData,
  ReportsGetPurchasesReportResponse,
  AlertsReadAlertsData,
  AlertsReadAlertsResponse,
  AlertsReadActiveAlertsResponse,
  AlertsReadAlertData,
  AlertsReadAlertResponse,
  AlertsResolveAlertData,
  AlertsResolveAlertResponse,
  AlertsReadAlertsByProductData,
  AlertsReadAlertsByProductResponse,
  KardexGetProductKardexData,
  KardexGetProductKardexResponse,
} from "./types.gen";

export class ItemsService {
  /**
   * Read Items
   * Retrieve items.
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @returns ItemsPublic Successful Response
   * @throws ApiError
   */
  public static readItems(
    data: ItemsReadItemsData = {}
  ): CancelablePromise<ItemsReadItemsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/items/",
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    });
  }

  /**
   * Create Item
   * Create new item.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns ItemPublic Successful Response
   * @throws ApiError
   */
  public static createItem(
    data: ItemsCreateItemData
  ): CancelablePromise<ItemsCreateItemResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/items/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    });
  }

  /**
   * Read Item
   * Get item by ID.
   * @param data The data for the request.
   * @param data.id
   * @returns ItemPublic Successful Response
   * @throws ApiError
   */
  public static readItem(
    data: ItemsReadItemData
  ): CancelablePromise<ItemsReadItemResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/items/{id}",
      path: {
        id: data.id,
      },
      errors: {
        422: "Validation Error",
      },
    });
  }

  /**
   * Update Item
   * Update an item.
   * @param data The data for the request.
   * @param data.id
   * @param data.requestBody
   * @returns ItemPublic Successful Response
   * @throws ApiError
   */
  public static updateItem(
    data: ItemsUpdateItemData
  ): CancelablePromise<ItemsUpdateItemResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/items/{id}",
      path: {
        id: data.id,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    });
  }

  /**
   * Delete Item
   * Delete an item.
   * @param data The data for the request.
   * @param data.id
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteItem(
    data: ItemsDeleteItemData
  ): CancelablePromise<ItemsDeleteItemResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/items/{id}",
      path: {
        id: data.id,
      },
      errors: {
        422: "Validation Error",
      },
    });
  }
}

export class LoginService {
  /**
   * Login Access Token
   * OAuth2 compatible token login, get an access token for future requests
   * @param data The data for the request.
   * @param data.formData
   * @returns Token Successful Response
   * @throws ApiError
   */
  public static loginAccessToken(
    data: LoginLoginAccessTokenData
  ): CancelablePromise<LoginLoginAccessTokenResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/login/access-token",
      formData: data.formData,
      mediaType: "application/x-www-form-urlencoded",
      errors: {
        422: "Validation Error",
      },
    });
  }

  /**
   * Test Token
   * Test access token
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static testToken(): CancelablePromise<LoginTestTokenResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/login/test-token",
    });
  }

  /**
   * Recover Password
   * Password Recovery
   * @param data The data for the request.
   * @param data.email
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static recoverPassword(
    data: LoginRecoverPasswordData
  ): CancelablePromise<LoginRecoverPasswordResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/password-recovery/{email}",
      path: {
        email: data.email,
      },
      errors: {
        422: "Validation Error",
      },
    });
  }

  /**
   * Reset Password
   * Reset password
   * @param data The data for the request.
   * @param data.requestBody
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static resetPassword(
    data: LoginResetPasswordData
  ): CancelablePromise<LoginResetPasswordResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/reset-password/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    });
  }

  /**
   * Recover Password Html Content
   * HTML Content for Password Recovery
   * @param data The data for the request.
   * @param data.email
   * @returns string Successful Response
   * @throws ApiError
   */
  public static recoverPasswordHtmlContent(
    data: LoginRecoverPasswordHtmlContentData
  ): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/password-recovery-html-content/{email}",
      path: {
        email: data.email,
      },
      errors: {
        422: "Validation Error",
      },
    });
  }
}

export class PrivateService {
  /**
   * Create User
   * Create a new user.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static createUser(
    data: PrivateCreateUserData
  ): CancelablePromise<PrivateCreateUserResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/private/users/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    });
  }
}

export class UsersService {
  /**
   * Read Users
   * Retrieve users.
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @returns UsersPublic Successful Response
   * @throws ApiError
   */
  public static readUsers(
    data: UsersReadUsersData = {}
  ): CancelablePromise<UsersReadUsersResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/users/",
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    });
  }

  /**
   * Create User
   * Create new user.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static createUser(
    data: UsersCreateUserData
  ): CancelablePromise<UsersCreateUserResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/users/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    });
  }

  /**
   * Read User Me
   * Get current user.
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/users/me",
    });
  }

  /**
   * Delete User Me
   * Delete own user.
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/users/me",
    });
  }

  /**
   * Update User Me
   * Update own user.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static updateUserMe(
    data: UsersUpdateUserMeData
  ): CancelablePromise<UsersUpdateUserMeResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/users/me",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    });
  }

  /**
   * Update Password Me
   * Update own password.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static updatePasswordMe(
    data: UsersUpdatePasswordMeData
  ): CancelablePromise<UsersUpdatePasswordMeResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/users/me/password",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    });
  }

  /**
   * Register User
   * Create new user without the need to be logged in.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static registerUser(
    data: UsersRegisterUserData
  ): CancelablePromise<UsersRegisterUserResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/users/signup",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    });
  }

  /**
   * Read User By Id
   * Get a specific user by id.
   * @param data The data for the request.
   * @param data.userId
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static readUserById(
    data: UsersReadUserByIdData
  ): CancelablePromise<UsersReadUserByIdResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/users/{user_id}",
      path: {
        user_id: data.userId,
      },
      errors: {
        422: "Validation Error",
      },
    });
  }

  /**
   * Update User
   * Update a user.
   * @param data The data for the request.
   * @param data.userId
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static updateUser(
    data: UsersUpdateUserData
  ): CancelablePromise<UsersUpdateUserResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/users/{user_id}",
      path: {
        user_id: data.userId,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    });
  }

  /**
   * Delete User
   * Delete a user.
   * @param data The data for the request.
   * @param data.userId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteUser(
    data: UsersDeleteUserData
  ): CancelablePromise<UsersDeleteUserResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/users/{user_id}",
      path: {
        user_id: data.userId,
      },
      errors: {
        422: "Validation Error",
      },
    });
  }
}

export class UtilsService {
  /**
   * Test Email
   * Test emails.
   * @param data The data for the request.
   * @param data.emailTo
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static testEmail(
    data: UtilsTestEmailData
  ): CancelablePromise<UtilsTestEmailResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/utils/test-email/",
      query: {
        email_to: data.emailTo,
      },
      errors: {
        422: "Validation Error",
      },
    });
  }

  /**
   * Health Check
   * @returns boolean Successful Response
   * @throws ApiError
   */
  public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/utils/health-check/",
    });
  }
}

// ============================================
// INVENTORY SERVICES
// ============================================

export class ProductsService {
  /**
   * Read Products
   * Retrieve products.
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @returns ProductsPublic Successful Response
   * @throws ApiError
   */
  public static readProducts(
    data: ProductsReadProductsData = {}
  ): CancelablePromise<ProductsReadProductsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/products/",
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    });
  }

  /**
   * Create Product
   * Create new product.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns ProductPublic Successful Response
   * @throws ApiError
   */
  public static createProduct(
    data: ProductsCreateProductData
  ): CancelablePromise<ProductsCreateProductResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/products/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    });
  }

  /**
   * Read Product
   * Get product by ID.
   * @param data The data for the request.
   * @param data.id
   * @returns ProductPublic Successful Response
   * @throws ApiError
   */
  public static readProduct(
    data: ProductsReadProductData
  ): CancelablePromise<ProductsReadProductResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/products/{id}",
      path: {
        id: data.id,
      },
      errors: {
        422: "Validation Error",
      },
    });
  }

  /**
   * Update Product
   * Update a product.
   * @param data The data for the request.
   * @param data.id
   * @param data.requestBody
   * @returns ProductPublic Successful Response
   * @throws ApiError
   */
  public static updateProduct(
    data: ProductsUpdateProductData
  ): CancelablePromise<ProductsUpdateProductResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/products/{id}",
      path: {
        id: data.id,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    });
  }

  /**
   * Delete Product
   * Delete a product.
   * @param data The data for the request.
   * @param data.id
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteProduct(
    data: ProductsDeleteProductData
  ): CancelablePromise<ProductsDeleteProductResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/products/{id}",
      path: {
        id: data.id,
      },
      errors: {
        422: "Validation Error",
      },
    });
  }
}

export class CategoriesService {
  /**
   * Read Categories
   * Retrieve categories.
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @returns CategoriesPublic Successful Response
   * @throws ApiError
   */
  public static readCategories(
    data: CategoriesReadCategoriesData = {}
  ): CancelablePromise<CategoriesReadCategoriesResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/categories/",
      query: {
        skip: data.skip,
        limit: data.limit,
        active_only: data.active_only,
      },
      errors: {
        422: "Validation Error",
      },
    });
  }

  /**
   * Create Category
   * Create new category.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns CategoryPublic Successful Response
   * @throws ApiError
   */
  public static createCategory(
    data: CategoriesCreateCategoryData
  ): CancelablePromise<CategoriesCreateCategoryResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/categories/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    });
  }

  /**
   * Read Category
   * Get category by ID.
   * @param data The data for the request.
   * @param data.id
   * @returns CategoryPublic Successful Response
   * @throws ApiError
   */
  public static readCategory(
    data: CategoriesReadCategoryData
  ): CancelablePromise<CategoriesReadCategoryResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/categories/{id}",
      path: {
        id: data.id,
      },
      errors: {
        422: "Validation Error",
      },
    });
  }

  /**
   * Update Category
   * Update a category.
   * @param data The data for the request.
   * @param data.id
   * @param data.requestBody
   * @returns CategoryPublic Successful Response
   * @throws ApiError
   */
  public static updateCategory(
    data: CategoriesUpdateCategoryData
  ): CancelablePromise<CategoriesUpdateCategoryResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/categories/{id}",
      path: {
        id: data.id,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    });
  }

  /**
   * Delete Category
   * Delete a category.
   * @param data The data for the request.
   * @param data.id
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteCategory(
    data: CategoriesDeleteCategoryData
  ): CancelablePromise<CategoriesDeleteCategoryResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/categories/{id}",
      path: {
        id: data.id,
      },
      errors: {
        422: "Validation Error",
      },
    });
  }
}

export class MovementsService {
  /**
   * Read Movements
   * Retrieve inventory movements. All authenticated users can view movements. Filters: product_id, movement_type, date range
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @param data.productId
   * @param data.movementType
   * @param data.startDate
   * @param data.endDate
   * @returns MovementsPublic Successful Response
   * @throws ApiError
   */
  public static readMovements(
    data: MovementsReadMovementsData = {}
  ): CancelablePromise<MovementsReadMovementsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/inventory-movements/",
      query: {
        skip: data.skip,
        limit: data.limit,
        product_id: data.product_id,
        movement_type: data.movement_type,
        start_date: data.start_date,
        end_date: data.end_date,
      },
      errors: {
        422: "Validation Error",
      },
    });
  }

  /**
   * Create Movement
   * Create new movement.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns MovementPublic Successful Response
   * @throws ApiError
   */
  public static createMovement(
    data: MovementsCreateMovementData
  ): CancelablePromise<MovementsCreateMovementResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/inventory-movements/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    });
  }

  /**
   * Read Movement
   * Get movement by ID.
   * @param data The data for the request.
   * @param data.id
   * @returns MovementPublic Successful Response
   * @throws ApiError
   */
  public static readMovement(
    data: MovementsReadMovementData
  ): CancelablePromise<MovementsReadMovementResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/inventory-movements/{id}",
      path: {
        id: data.id,
      },
      errors: {
        422: "Validation Error",
      },
    });
  }
}

export class ReportsService {
  /**
   * Get Sales Report
   * Get sales report.
   * @param data The data for the request.
   * @param data.startDate
   * @param data.endDate
   * @returns SalesReport Successful Response
   * @throws ApiError
   */
  public static getSalesReport(
    data: ReportsGetSalesReportData = {}
  ): CancelablePromise<ReportsGetSalesReportResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/reports/sales",
      query: {
        start_date: data.start_date,
        end_date: data.end_date,
      },
      errors: {
        422: "Validation Error",
      },
    });
  }

  /**
   * Get Purchases Report
   * Get purchases report.
   * @param data The data for the request.
   * @param data.startDate
   * @param data.endDate
   * @returns PurchasesReport Successful Response
   * @throws ApiError
   */
  public static getPurchasesReport(
    data: ReportsGetPurchasesReportData = {}
  ): CancelablePromise<ReportsGetPurchasesReportResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/reports/purchases",
      query: {
        start_date: data.start_date,
        end_date: data.end_date,
      },
      errors: {
        422: "Validation Error",
      },
    });
  }
}

export class AlertsService {
  /**
   * Read Alerts
   * Retrieve alerts. All authenticated users can view alerts. Filters: resolved (True/False/None for all), product_id, alert_type
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @param data.resolved
   * @param data.product_id
   * @param data.alert_type
   * @returns AlertsPublic Successful Response
   * @throws ApiError
   */
  public static readAlerts(
    data: AlertsReadAlertsData = {}
  ): CancelablePromise<AlertsReadAlertsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/alerts/",
      query: {
        skip: data.skip,
        limit: data.limit,
        resolved: data.resolved,
        product_id: data.product_id,
        alert_type: data.alert_type,
      },
      errors: {
        422: "Validation Error",
      },
    });
  }

  /**
   * Read Active Alerts
   * Retrieve only active (unresolved) alerts. Useful for dashboard/monitoring.
   * @returns AlertsPublic Successful Response
   * @throws ApiError
   */
  public static readActiveAlerts(): CancelablePromise<AlertsReadActiveAlertsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/alerts/active",
      errors: {
        422: "Validation Error",
      },
    });
  }

  /**
   * Read Alert
   * Get alert by ID. All authenticated users can view alerts.
   * @param data The data for the request.
   * @param data.id
   * @returns AlertPublic Successful Response
   * @throws ApiError
   */
  public static readAlert(
    data: AlertsReadAlertData
  ): CancelablePromise<AlertsReadAlertResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/alerts/{id}",
      path: {
        id: data.id,
      },
      errors: {
        422: "Validation Error",
      },
    });
  }

  /**
   * Resolve Alert
   * Resolve an alert manually. Only administrador can resolve alerts. Note: Alerts are also auto-resolved when stock is replenished.
   * @param data The data for the request.
   * @param data.id
   * @param data.requestBody
   * @returns AlertPublic Successful Response
   * @throws ApiError
   */
  public static resolveAlert(
    data: AlertsResolveAlertData
  ): CancelablePromise<AlertsResolveAlertResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/alerts/{id}/resolve",
      path: {
        id: data.id,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    });
  }

  /**
   * Read Alerts By Product
   * Get all alerts for a specific product. Filter by resolved status (optional).
   * @param data The data for the request.
   * @param data.productId
   * @param data.resolved
   * @returns AlertsPublic Successful Response
   * @throws ApiError
   */
  public static readAlertsByProduct(
    data: AlertsReadAlertsByProductData
  ): CancelablePromise<AlertsReadAlertsByProductResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/alerts/product/{product_id}",
      path: {
        product_id: data.productId,
      },
      query: {
        resolved: data.resolved,
      },
      errors: {
        422: "Validation Error",
      },
    });
  }
}

export class KardexService {
  /**
   * Get Product Kardex
   * Get Kardex (movement history) for a product. All authenticated users can view kardex.
   * Returns:
   * - Product information
   * - List of movements (filtered by date if provided)
   * - Total number of movements
   * - Current stock
   * - Stock status
   * @param data The data for the request.
   * @param data.productId
   * @param data.start_date
   * @param data.end_date
   * @param data.skip
   * @param data.limit
   * @returns ProductKardex Successful Response
   * @throws ApiError
   */
  public static getProductKardex(
    data: KardexGetProductKardexData
  ): CancelablePromise<KardexGetProductKardexResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/kardex/{product_id}",
      path: {
        product_id: data.productId,
      },
      query: {
        start_date: data.start_date,
        end_date: data.end_date,
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    });
  }
}
