// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
  grant_type?: string | null;
  username: string;
  password: string;
  scope?: string;
  client_id?: string | null;
  client_secret?: string | null;
};

export type HTTPValidationError = {
  detail?: Array<ValidationError>;
};

export type ItemCreate = {
  title: string;
  description?: string | null;
};

export type ItemPublic = {
  title: string;
  description?: string | null;
  id: string;
  owner_id: string;
};

export type ItemsPublic = {
  data: Array<ItemPublic>;
  count: number;
};

export type ItemUpdate = {
  title?: string | null;
  description?: string | null;
};

export type Message = {
  message: string;
};

export type NewPassword = {
  token: string;
  new_password: string;
};

export type PrivateUserCreate = {
  email: string;
  password: string;
  full_name: string;
  is_verified?: boolean;
};

export type Token = {
  access_token: string;
  token_type?: string;
};

export type UpdatePassword = {
  current_password: string;
  new_password: string;
};

export type UserCreate = {
  email: string;
  is_active?: boolean;
  is_superuser?: boolean;
  full_name?: string | null;
  password: string;
};

export type UserPublic = {
  email: string;
  is_active?: boolean;
  is_superuser?: boolean;
  full_name?: string | null;
  id: string;
};

export type UserRegister = {
  email: string;
  password: string;
  full_name?: string | null;
};

export type UsersPublic = {
  data: Array<UserPublic>;
  count: number;
};

export type UserUpdate = {
  email?: string | null;
  is_active?: boolean;
  is_superuser?: boolean;
  full_name?: string | null;
  password?: string | null;
};

export type UserUpdateMe = {
  full_name?: string | null;
  email?: string | null;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};

// ============================================
// INVENTORY TYPES
// ============================================

export type ProductCreate = {
  name: string;
  description?: string | null;
  price: number;
  stock: number;
  category_id?: string | null;
};

export type ProductPublic = {
  name: string;
  description?: string | null;
  price: number;
  stock: number;
  category_id?: string | null;
  id: string;
};

export type ProductsPublic = {
  data: Array<ProductPublic>;
  count: number;
};

export type ProductUpdate = {
  name?: string | null;
  description?: string | null;
  price?: number | null;
  stock?: number | null;
  category_id?: string | null;
};

export type CategoryCreate = {
  name: string;
  description?: string | null;
};

export type CategoryPublic = {
  name: string;
  description?: string | null;
  id: string;
};

export type CategoriesPublic = {
  data: Array<CategoryPublic>;
  count: number;
};

export type CategoryUpdate = {
  name?: string | null;
  description?: string | null;
};

export type MovementType = "entrada" | "salida";

export type MovementCreate = {
  product_id: string;
  quantity: number;
  movement_type: MovementType;
  notes?: string | null;
};

export type MovementPublic = {
  product_id: string;
  quantity: number;
  movement_type: MovementType;
  notes?: string | null;
  id: string;
  created_at: string;
};

export type MovementsPublic = {
  data: Array<MovementPublic>;
  count: number;
};

export type MovementUpdate = {
  quantity?: number | null;
  movement_type?: MovementType | null;
  notes?: string | null;
};

export type SalesReport = {
  start_date?: string | null;
  end_date?: string | null;
  total_sales: number;
  total_quantity: number;
};

export type PurchasesReport = {
  start_date?: string | null;
  end_date?: string | null;
  total_purchases: number;
  total_quantity: number;
};

// ============================================
// REQUEST/RESPONSE TYPES
// ============================================

// Items
export type ItemsReadItemsData = {
  limit?: number;
  skip?: number;
};

export type ItemsReadItemsResponse = ItemsPublic;

export type ItemsCreateItemData = {
  requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = ItemPublic;

export type ItemsReadItemData = {
  id: string;
};

export type ItemsReadItemResponse = ItemPublic;

export type ItemsUpdateItemData = {
  id: string;
  requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = ItemPublic;

export type ItemsDeleteItemData = {
  id: string;
};

export type ItemsDeleteItemResponse = Message;

// Login
export type LoginLoginAccessTokenData = {
  formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = Token;

export type LoginTestTokenResponse = UserPublic;

export type LoginRecoverPasswordData = {
  email: string;
};

export type LoginRecoverPasswordResponse = Message;

export type LoginResetPasswordData = {
  requestBody: NewPassword;
};

export type LoginResetPasswordResponse = Message;

export type LoginRecoverPasswordHtmlContentData = {
  email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = string;

// Private
export type PrivateCreateUserData = {
  requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = UserPublic;

// Users
export type UsersReadUsersData = {
  limit?: number;
  skip?: number;
};

export type UsersReadUsersResponse = UsersPublic;

export type UsersCreateUserData = {
  requestBody: UserCreate;
};

export type UsersCreateUserResponse = UserPublic;

export type UsersReadUserMeResponse = UserPublic;

export type UsersDeleteUserMeResponse = Message;

export type UsersUpdateUserMeData = {
  requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = UserPublic;

export type UsersUpdatePasswordMeData = {
  requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = Message;

export type UsersRegisterUserData = {
  requestBody: UserRegister;
};

export type UsersRegisterUserResponse = UserPublic;

export type UsersReadUserByIdData = {
  userId: string;
};

export type UsersReadUserByIdResponse = UserPublic;

export type UsersUpdateUserData = {
  requestBody: UserUpdate;
  userId: string;
};

export type UsersUpdateUserResponse = UserPublic;

export type UsersDeleteUserData = {
  userId: string;
};

export type UsersDeleteUserResponse = Message;

// Utils
export type UtilsTestEmailData = {
  emailTo: string;
};

export type UtilsTestEmailResponse = Message;

export type UtilsHealthCheckResponse = boolean;

// Products
export type ProductsReadProductsData = {
  limit?: number;
  skip?: number;
};

export type ProductsReadProductsResponse = ProductsPublic;

export type ProductsCreateProductData = {
  requestBody: ProductCreate;
};

export type ProductsCreateProductResponse = ProductPublic;

export type ProductsReadProductData = {
  id: string;
};

export type ProductsReadProductResponse = ProductPublic;

export type ProductsUpdateProductData = {
  id: string;
  requestBody: ProductUpdate;
};

export type ProductsUpdateProductResponse = ProductPublic;

export type ProductsDeleteProductData = {
  id: string;
};

export type ProductsDeleteProductResponse = Message;

// Categories
export type CategoriesReadCategoriesData = {
  limit?: number;
  skip?: number;
};

export type CategoriesReadCategoriesResponse = CategoriesPublic;

export type CategoriesCreateCategoryData = {
  requestBody: CategoryCreate;
};

export type CategoriesCreateCategoryResponse = CategoryPublic;

export type CategoriesReadCategoryData = {
  id: string;
};

export type CategoriesReadCategoryResponse = CategoryPublic;

export type CategoriesUpdateCategoryData = {
  id: string;
  requestBody: CategoryUpdate;
};

export type CategoriesUpdateCategoryResponse = CategoryPublic;

export type CategoriesDeleteCategoryData = {
  id: string;
};

export type CategoriesDeleteCategoryResponse = Message;

// Movements
export type MovementsReadMovementsData = {
  limit?: number;
  skip?: number;
};

export type MovementsReadMovementsResponse = MovementsPublic;

export type MovementsCreateMovementData = {
  requestBody: MovementCreate;
};

export type MovementsCreateMovementResponse = MovementPublic;

export type MovementsReadMovementData = {
  id: string;
};

export type MovementsReadMovementResponse = MovementPublic;

export type MovementsUpdateMovementData = {
  id: string;
  requestBody: MovementUpdate;
};

export type MovementsUpdateMovementResponse = MovementPublic;

export type MovementsDeleteMovementData = {
  id: string;
};

export type MovementsDeleteMovementResponse = Message;

// Reports
export type ReportsGetSalesReportData = {
  startDate?: string | null;
  endDate?: string | null;
};

export type ReportsGetSalesReportResponse = SalesReport;

export type ReportsGetPurchasesReportData = {
  startDate?: string | null;
  endDate?: string | null;
};

export type ReportsGetPurchasesReportResponse = PurchasesReport;
