// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
  grant_type?: string | null;
  username: string;
  password: string;
  scope?: string;
  client_id?: string | null;
  client_secret?: string | null;
};

export type HTTPValidationError = {
  detail?: Array<ValidationError>;
};

export type ItemCreate = {
  title: string;
  description?: string | null;
};

export type ItemPublic = {
  title: string;
  description?: string | null;
  id: string;
  owner_id: string;
};

export type ItemsPublic = {
  data: Array<ItemPublic>;
  count: number;
};

export type ItemUpdate = {
  title?: string | null;
  description?: string | null;
};

export type Message = {
  message: string;
};

export type NewPassword = {
  token: string;
  new_password: string;
};

export type PrivateUserCreate = {
  email: string;
  password: string;
  full_name: string;
  is_verified?: boolean;
};

export type Token = {
  access_token: string;
  token_type?: string;
};

export type UpdatePassword = {
  current_password: string;
  new_password: string;
};

export type UserRole = "ADMINISTRADOR" | "AUXILIAR" | "VENDEDOR";

export type UserCreate = {
  email: string;
  is_active?: boolean;
  is_superuser?: boolean;
  full_name?: string | null;
  role: UserRole;
  password: string;
};

export type UserPublic = {
  email: string;
  is_active?: boolean;
  is_superuser?: boolean;
  full_name?: string | null;
  role: UserRole;
  id: string;
};

export type UserRegister = {
  email: string;
  password: string;
  full_name?: string | null;
};

export type UsersPublic = {
  data: Array<UserPublic>;
  count: number;
};

export type UserUpdate = {
  email?: string | null;
  is_active?: boolean;
  is_superuser?: boolean;
  full_name?: string | null;
  role?: UserRole | null;
  password?: string | null;
};

export type UserUpdateMe = {
  full_name?: string | null;
  email?: string | null;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};

// ============================================
// INVENTORY TYPES
// ============================================

export type ProductCreate = {
  sku: string;
  name: string;
  description?: string | null;
  category_id?: string | null;
  unit_price: number;
  sale_price?: number | null;
  unit_of_measure: string;
  min_stock: number;
  is_active?: boolean;
};

export type ProductPublic = {
  sku: string;
  name: string;
  description?: string | null;
  category_id?: string | null;
  unit_price: string;
  sale_price?: string | null;
  unit_of_measure: string;
  min_stock: number;
  is_active: boolean;
  id: string;
  current_stock: number;
  created_at: string;
  updated_at: string;
  created_by: string;
};

export type ProductsPublic = {
  data: Array<ProductPublic>;
  count: number;
};

export type ProductUpdate = {
  sku?: string | null;
  name?: string | null;
  description?: string | null;
  category_id?: string | null;
  unit_price?: number | null;
  sale_price?: number | null;
  unit_of_measure?: string | null;
  min_stock?: number | null;
  is_active?: boolean | null;
};

export type CategoryCreate = {
  name: string;
  description?: string | null;
  is_active?: boolean | null;
};

export type CategoryPublic = {
  name: string;
  description?: string | null;
  is_active?: boolean | null;
  id: string;
};

export type CategoriesPublic = {
  data: Array<CategoryPublic>;
  count: number;
};

export type CategoryUpdate = {
  name?: string | null;
  description?: string | null;
  is_active?: boolean | null;
};

export type MovementType =
  | "ENTRADA_COMPRA"
  | "SALIDA_VENTA"
  | "AJUSTE_CONTEO"
  | "AJUSTE_MERMA"
  | "DEVOLUCION_CLIENTE"
  | "DEVOLUCION_PROVEEDOR";

export type MovementCreate = {
  product_id: string;
  quantity: number;
  movement_type: MovementType;
  reference_number?: string | null;
  notes?: string | null;
  unit_price?: number | null;
  movement_date?: string | null;
};

export type MovementPublic = {
  product_id: string;
  quantity: number;
  movement_type: MovementType;
  reference_number?: string | null;
  notes?: string | null;
  unit_price?: string | null;
  movement_date: string;
  id: string;
  total_amount?: string | null;
  stock_before: number;
  stock_after: number;
  created_at: string;
  created_by: string;
};

export type MovementsPublic = {
  data: Array<MovementPublic>;
  count: number;
};

export type MovementUpdate = {
  quantity?: number | null;
  movement_type?: MovementType | null;
  notes?: string | null;
};

// ============================================
// REPORTS TYPES
// ============================================

export type AlertType = "LOW_STOCK" | "OUT_OF_STOCK";

export type AlertPublic = {
  product_id: string;
  alert_type: AlertType;
  current_stock: number;
  min_stock: number;
  notes?: string | null;
  id: string;
  is_resolved: boolean;
  resolved_at?: string | null;
  resolved_by?: string | null;
  created_at: string;
};

export type AlertsPublic = {
  data: Array<AlertPublic>;
  count: number;
};

export type AlertResolve = {
  is_resolved: boolean;
  notes?: string | null;
};

export type ProductKardex = {
  product: ProductPublic;
  movements: Array<MovementPublic>;
  total_movements: number;
  current_stock: number;
  stock_status: string;
};

export type InventoryReportItem = {
  sku: string;
  name: string;
  category_name?: string | null;
  current_stock: number;
  min_stock: number;
  unit_price: string;
  sale_price?: string | null;
  total_value: string;
  stock_status: string;
  unit_of_measure: string;
};

export type InventoryReport = {
  generated_at: string;
  total_products: number;
  total_value: string;
  low_stock_count: number;
  out_of_stock_count: number;
  items: Array<InventoryReportItem>;
};

export type SalesReportItem = {
  product_sku: string;
  product_name: string;
  quantity_sold: number;
  total_sales: string;
  movement_count: number;
};

export type SalesReport = {
  generated_at: string;
  start_date?: string | null;
  end_date?: string | null;
  total_sales: string;
  total_items_sold: number;
  total_transactions: number;
  items: Array<SalesReportItem>;
};

export type PurchasesReportItem = {
  product_sku: string;
  product_name: string;
  quantity_purchased: number;
  total_cost: string;
  movement_count: number;
};

export type PurchasesReport = {
  generated_at: string;
  start_date?: string | null;
  end_date?: string | null;
  total_purchases: string;
  total_items_purchased: number;
  total_transactions: number;
  items: Array<PurchasesReportItem>;
};

// ============================================
// REQUEST/RESPONSE TYPES
// ============================================

// Items
export type ItemsReadItemsData = {
  limit?: number;
  skip?: number;
};

export type ItemsReadItemsResponse = ItemsPublic;

export type ItemsCreateItemData = {
  requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = ItemPublic;

export type ItemsReadItemData = {
  id: string;
};

export type ItemsReadItemResponse = ItemPublic;

export type ItemsUpdateItemData = {
  id: string;
  requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = ItemPublic;

export type ItemsDeleteItemData = {
  id: string;
};

export type ItemsDeleteItemResponse = Message;

// Login
export type LoginLoginAccessTokenData = {
  formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = Token;

export type LoginTestTokenResponse = UserPublic;

export type LoginRecoverPasswordData = {
  email: string;
};

export type LoginRecoverPasswordResponse = Message;

export type LoginResetPasswordData = {
  requestBody: NewPassword;
};

export type LoginResetPasswordResponse = Message;

export type LoginRecoverPasswordHtmlContentData = {
  email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = string;

// Private
export type PrivateCreateUserData = {
  requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = UserPublic;

// Users
export type UsersReadUsersData = {
  limit?: number;
  skip?: number;
};

export type UsersReadUsersResponse = UsersPublic;

export type UsersCreateUserData = {
  requestBody: UserCreate;
};

export type UsersCreateUserResponse = UserPublic;

export type UsersReadUserMeResponse = UserPublic;

export type UsersDeleteUserMeResponse = Message;

export type UsersUpdateUserMeData = {
  requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = UserPublic;

export type UsersUpdatePasswordMeData = {
  requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = Message;

export type UsersRegisterUserData = {
  requestBody: UserRegister;
};

export type UsersRegisterUserResponse = UserPublic;

export type UsersReadUserByIdData = {
  userId: string;
};

export type UsersReadUserByIdResponse = UserPublic;

export type UsersUpdateUserData = {
  requestBody: UserUpdate;
  userId: string;
};

export type UsersUpdateUserResponse = UserPublic;

export type UsersDeleteUserData = {
  userId: string;
};

export type UsersDeleteUserResponse = Message;

// Utils
export type UtilsTestEmailData = {
  emailTo: string;
};

export type UtilsTestEmailResponse = Message;

export type UtilsHealthCheckResponse = boolean;

// Products
export type ProductsReadProductsData = {
  limit?: number;
  skip?: number;
  active_only?: boolean;
  category_id?: string | null;
  search?: string | null;
  low_stock_only?: boolean;
};

export type ProductsReadProductsResponse = ProductsPublic;

export type ProductsCreateProductData = {
  requestBody: ProductCreate;
};

export type ProductsCreateProductResponse = ProductPublic;

export type ProductsReadProductData = {
  id: string;
};

export type ProductsReadProductResponse = ProductPublic;

export type ProductsUpdateProductData = {
  id: string;
  requestBody: ProductUpdate;
};

export type ProductsUpdateProductResponse = ProductPublic;

export type ProductsDeleteProductData = {
  id: string;
};

export type ProductsDeleteProductResponse = Message;

// Categories
export type CategoriesReadCategoriesData = {
  limit?: number;
  skip?: number;
  active_only?: boolean;
};

export type CategoriesReadCategoriesResponse = CategoriesPublic;

export type CategoriesCreateCategoryData = {
  requestBody: CategoryCreate;
};

export type CategoriesCreateCategoryResponse = CategoryPublic;

export type CategoriesReadCategoryData = {
  id: string;
};

export type CategoriesReadCategoryResponse = CategoryPublic;

export type CategoriesUpdateCategoryData = {
  id: string;
  requestBody: CategoryUpdate;
};

export type CategoriesUpdateCategoryResponse = CategoryPublic;

export type CategoriesDeleteCategoryData = {
  id: string;
};

export type CategoriesDeleteCategoryResponse = Message;

// Movements
export type MovementsReadMovementsData = {
  limit?: number;
  skip?: number;
  product_id?: string | null;
  movement_type?: MovementType | null;
  start_date?: string | null;
  end_date?: string | null;
};

export type MovementsReadMovementsResponse = MovementsPublic;

export type MovementsCreateMovementData = {
  requestBody: MovementCreate;
};

export type MovementsCreateMovementResponse = MovementPublic;

export type MovementsReadMovementData = {
  id: string;
};

export type MovementsReadMovementResponse = MovementPublic;

export type MovementsUpdateMovementData = {
  id: string;
  requestBody: MovementUpdate;
};

export type MovementsUpdateMovementResponse = MovementPublic;

export type MovementsDeleteMovementData = {
  id: string;
};

export type MovementsDeleteMovementResponse = Message;

// Reports
export type ReportsGetInventoryReportData = {
  category_id?: string | null;
  active_only?: boolean;
};

export type ReportsGetInventoryReportResponse = InventoryReport;

export type ReportsExportInventoryCsvData = {
  category_id?: string | null;
  active_only?: boolean;
};

export type ReportsExportInventoryCsvResponse = string;

export type ReportsGetSalesReportData = {
  start_date?: string | null;
  end_date?: string | null;
  category_id?: string | null;
};

export type ReportsGetSalesReportResponse = SalesReport;

export type ReportsExportSalesCsvData = {
  start_date?: string | null;
  end_date?: string | null;
  category_id?: string | null;
};

export type ReportsExportSalesCsvResponse = string;

export type ReportsGetPurchasesReportData = {
  start_date?: string | null;
  end_date?: string | null;
  category_id?: string | null;
};

export type ReportsGetPurchasesReportResponse = PurchasesReport;

export type ReportsExportPurchasesCsvData = {
  start_date?: string | null;
  end_date?: string | null;
  category_id?: string | null;
};

export type ReportsExportPurchasesCsvResponse = string;

// Alerts
export type AlertsReadAlertsData = {
  limit?: number;
  skip?: number;
  resolved?: boolean | null;
  product_id?: string | null;
  alert_type?: AlertType | null;
};

export type AlertsReadAlertsResponse = AlertsPublic;

export type AlertsReadActiveAlertsResponse = AlertsPublic;

export type AlertsReadAlertData = {
  id: string;
};

export type AlertsReadAlertResponse = AlertPublic;

export type AlertsResolveAlertData = {
  id: string;
  requestBody: AlertResolve;
};

export type AlertsResolveAlertResponse = AlertPublic;

export type AlertsReadAlertsByProductData = {
  productId: string;
  resolved?: boolean | null;
};

export type AlertsReadAlertsByProductResponse = AlertsPublic;

// Kardex
export type KardexGetProductKardexData = {
  productId: string;
  start_date?: string | null;
  end_date?: string | null;
  skip?: number;
  limit?: number;
};

export type KardexGetProductKardexResponse = ProductKardex;
