/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutUsersImport } from './routes/_layout/users'
import { Route as LayoutSettingsImport } from './routes/_layout/settings'
import { Route as LayoutReportsImport } from './routes/_layout/reports'
import { Route as LayoutProductsImport } from './routes/_layout/products'
import { Route as LayoutMovementsImport } from './routes/_layout/movements'
import { Route as LayoutCategoriesImport } from './routes/_layout/categories'
import { Route as LayoutAlertsImport } from './routes/_layout/Alerts'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutUsersRoute = LayoutUsersImport.update({
  path: '/users',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSettingsRoute = LayoutSettingsImport.update({
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutReportsRoute = LayoutReportsImport.update({
  path: '/reports',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutProductsRoute = LayoutProductsImport.update({
  path: '/products',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutMovementsRoute = LayoutMovementsImport.update({
  path: '/movements',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutCategoriesRoute = LayoutCategoriesImport.update({
  path: '/categories',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAlertsRoute = LayoutAlertsImport.update({
  path: '/Alerts',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_layout/Alerts': {
      preLoaderRoute: typeof LayoutAlertsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/categories': {
      preLoaderRoute: typeof LayoutCategoriesImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/movements': {
      preLoaderRoute: typeof LayoutMovementsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/products': {
      preLoaderRoute: typeof LayoutProductsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/reports': {
      preLoaderRoute: typeof LayoutReportsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/settings': {
      preLoaderRoute: typeof LayoutSettingsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/users': {
      preLoaderRoute: typeof LayoutUsersImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutRoute.addChildren([
    LayoutAlertsRoute,
    LayoutCategoriesRoute,
    LayoutMovementsRoute,
    LayoutProductsRoute,
    LayoutReportsRoute,
    LayoutSettingsRoute,
    LayoutUsersRoute,
    LayoutIndexRoute,
  ]),
  LoginRoute,
])

/* prettier-ignore-end */
